//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animal_Info.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int ID_animal { get; set; }
        public string Name { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> ID_master { get; set; }
    
        public virtual Master Master { get; set; }
    }
}
